<?php

	// N2 Framework Yverdon Template Event Constants
	define('N2F_TPLEVT_SET_BASE',						'N2F_TPLEVT_SET_BASE');
	define('N2F_TPLEVT_SET_MODULE',					'N2F_TPLEVT_SET_MODULE');
	define('N2F_TPLEVT_SET_SKIN',						'N2F_TPLEVT_SET_SKIN');
	define('N2F_TPLEVT_SET_FILE',						'N2F_TPLEVT_SET_FILE');
	define('N2F_TPLEVT_SET_FIELD',					'N2F_TPLEVT_SET_FIELD');
	define('N2F_TPLEVT_SET_FIELDS',					'N2F_TPLEVT_SET_FIELDS');
	define('N2F_TPLEVT_SET_EXPIRE',					'N2F_TPLEVT_SET_EXPIRE');
	define('N2F_TPLEVT_SET_BINDING',					'N2F_TPLEVT_SET_BINDING');
	define('N2F_TPLEVT_SET_BINDINGS',					'N2F_TPLEVT_SET_BINDINGS');
	define('N2F_TPLEVT_RENDER',						'N2F_TPLEVT_RENDER');
	define('N2F_TPLEVT_FETCH',						'N2F_TPLEVT_FETCH');
	define('N2F_TPLEVT_DISPLAY',						'N2F_TPLEVT_DISPLAY');
	define('N2F_TPLEVT_SET_ALIAS',					'N2F_TPLEVT_SET_ALIAS');
	define('N2F_TPLEVT_SET_GALIAS',					'N2F_TPLEVT_SET_GALIAS');
	define('N2F_TPLEVT_BASE_SET',						'N2F_TPLEVT_BASE_SET');
	define('N2F_TPLEVT_MODULE_SET',					'N2F_TPLEVT_MODULE_SET');
	define('N2F_TPLEVT_SKIN_SET',						'N2F_TPLEVT_SKIN_SET');
	define('N2F_TPLEVT_FILE_SET',						'N2F_TPLEVT_FILE_SET');
	define('N2F_TPLEVT_FIELD_SET',					'N2F_TPLEVT_FIELD_SET');
	define('N2F_TPLEVT_FIELDS_SET',					'N2F_TPLEVT_FIELDS_SET');
	define('N2F_TPLEVT_EXPIRE_SET',					'N2F_TPLEVT_EXPIRE_SET');
	define('N2F_TPLEVT_BINDING_SET',					'N2F_TPLEVT_BINDING_SET');
	define('N2F_TPLEVT_BINDINGS_SET',					'N2F_TPLEVT_BINDINGS_SET');
	define('N2F_TPLEVT_RENDERED',						'N2F_TPLEVT_RENDERED');
	define('N2F_TPLEVT_FETCHED',						'N2F_TPLEVT_FETCHED');
	define('N2F_TPLEVT_DISPLAYED',					'N2F_TPLEVT_DISPLAYED');
	define('N2F_TPLEVT_ALIAS_SET',					'N2F_TPLEVT_ALIAS_SET');
	define('N2F_TPLEVT_GALIAS_SET',					'N2F_TPLEVT_GALIAS_SET');

	// N2 Framework Yverdon Template Error Constants
	define('N2F_ERROR_TPL_EXTENSION_NOT_LOADED', 		'0001');
	define('N2F_ERROR_TPL_SIMPLEXML_PARSE',				'0002');

	// N2 Framework Yverdon Template Notice Constants
	define('N2F_NOTICE_TPL_BASE_SET',					'0001');
	define('N2F_NOTICE_TPL_MODULE_SET',				'0002');
	define('N2F_NOTICE_TPL_SKIN_SET',					'0003');
	define('N2F_NOTICE_TPL_FILE_SET',					'0004');
	define('N2F_NOTICE_TPL_FIELD_SET',					'0005');
	define('N2F_NOTICE_TPL_FIELDS_SET',				'0006');
	define('N2F_NOTICE_TPL_EXPIRE_SET',				'0007');
	define('N2F_NOTICE_TPL_BINDING_SET',				'0008');
	define('N2F_NOTICE_TPL_BINDINGS_SET',				'0009');
	define('N2F_NOTICE_TPL_RENDER',					'0010');
	define('N2F_NOTICE_TPL_FETCH',					'0011');
	define('N2F_NOTICE_TPL_DISPLAY',					'0012');
	define('N2F_NOTICE_TPL_GFIELD_SET',				'0013');
	define('N2F_NOTICE_TPL_ALIAS_SET',					'0014');
	define('N2F_NOTICE_TPL_GALIAS_SET',				'0015');
	define('N2F_NOTICE_TPL_GBINDING_SET',				'0016');

?>